### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jmp75** [AtrCheema/AI4Water#14]
Hi,

First, thank you for this package. I am planning to use it in a research project over the coming year at least, and look forward to do so, and hopefully offer to contribute back.

I tried to set up a virtual environment (venv or conda) suitable for ai4water, and it was a bit bumpy. Not unexpected mind you, having been there several times. I also tried installing both tensorflow and pytorch in the same environment, which was perhaps overly ambitious and risky.

A virtual environment with a `pip install tensorflow` is easy to set up, but this does assume that the right versions of libcdnn and cuda are installed at the OS level, which is not a trivial endeavour.

I've had success in the past reliably installing a conda environment for pytorch and fastai, including suitable versions cuDNN libraries.

I am planning to document ways to reliably install environments with a mix  of docker, conda, pip (as necessary, the lesser the better) to get ai4water running,

If you have any advice on what environments you have to run ai4water, I'd welcome tips.

J-M

**Comment by AtrCheema** [comment]
I strongly recommend you not to install tensorflow-gpu and pytorch-gpu in same environment. Have separate environments for tensorflow-gpu and pytorch-gpu. I do have tensorflow 1.1.5  cpu and pytorch 1.8.0 cpu in one environment but if you try to do this for gpu versions, then this will bring conflict in one or other. 

The best way to setup environment for ai4water is using conda, then install requirements either from requirements.txt or requirements_all.txt. If you want tensorlfow-gpu then I recommend you to do so using conda but then comment out the line in requirements.txt/requirements_all.txt file.
